`timescale 1ns/1ps
module mach_logic_batky_tb;
reg a;
reg b;
reg c;
wire y;
logic_batky uut(
    .a(a),
    .b(b),
    .c(c),
    .y(y)
);
initial begin
    $dumpfile("mach_logic_batky.vcd");
    $dumpvars(0,mach_logic_batky_tb);
end
initial begin
    a=0;b=0;c=0;
    #10;
    a=0;b=0;c=1;
    #10;
    a=0;b=1;c=0;
    #10;
    a=0;b=1;c=1;
    #10;
    a=1;b=0;c=0;
    #10;
    a=1;b=0;c=1;
    #10;
    a=1;b=1;c=0;
    #10;
    a=1;b=1;c=1;
    #10;
    $finish;
end
initial begin
    $monitor("time=%0t a=%b b=%b c=%b y=%b",
                    $time,a,b,c,y);
end
endmodule